model:
    name: 'SelfSupModel'
    depth_net:
        name: 'PackNet01'
        version: '1A'
    pose_net:
        name: 'PoseNet'
        version: ''
    params:
        crop: 'garg'
        min_depth: 0.0
        max_depth: 80.0
datasets:
    augmentation:
        image_shape: (192, 640)
    test:
        dataset: ['KITTI']
        path: ['/home/SamruddhiPai/Desktop/monocular_3d_boundingBox/code_dev/frustum-convnet/data/kitti/training']
        split: ['train_split.txt']
        depth_type: ['velodyne']
save:
    folder: '/home/SamruddhiPai/Desktop/monocular_3d_boundingBox/code_dev/frustum-convnet/data/kitti/training/velodyne'
    depth:
        rgb: False
        viz: False
        npz: True
        png: True
